---
- name: upgrade repositories
  package:
    upgrade: dist
    update_cache: yes

- name: install apt-transport-https
  package:
    name: apt-transport-https 
    state: latest

- name: install ca-certificates
  package:
    name: ca-certificates
    state: latest

- name: install docker
  pip:
    name: docker-py
    state: latest

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest

- name: created a docker group
  group:
    name: docker
    state: present

- name: adding group to user
  user:
    name: '{{ user }}'
    groups: docker
    append: yes

