---
- name: upgrade repositories
  package:
    upgrade: dist
    update_cache: yes

- name: if not exist docker.list
  file:
    path: '{{ docker_list_path }}'
  register: result
  ignore_errors: true

- name: create docker.list
  file:
    path: '{{ docker_list_path }}'
    state: touch
  when: result|failed

- name: adding repository 
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: '{{ repository }}'
    state: present
  notify: add_repo
  
- name: install apt-transport-httpss 
  package:
    name: apt-transport-https 
    state: latest

- name: install ca-certificates
  package:
    name: ca-certificates
    state: latest

- name: add key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80 
    id: 58118E89F3A912897C070ADBF76221572C52609D 

- name: install docker-engine
  package:
    name: docker-engine
    state: present 

- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest

- name: created a docker group
  group:
    name: docker
    state: present

- name: adding group to user
  user:
    name: '{{ user }}'
    groups: docker
    append: yes

- name: initiating docker service
  systemd:
    name: docker
    state: started
    enabled: true
